### PR TITLE
Remove copyleft files

### PR DESCRIPTION
**Pull request by EvanGSullivan**

### CODE REVIEW

**Review by saturley-hall — APPROVED** [review]

**Comment by ranjeethmahankali** [comment]
What are all these test failures?

**Review by ranjeethmahankali — COMMENTED** [review]
What are all the failures? Do we not care? Should we remove them?

**Comment by EvanGSullivan** [comment]
> What are all the failures? Do we not care? Should we remove them?

I wasn't sure where they came from. Previous PRs of ours (like #9) didn't have them, and I didn't add them. I'll see if I can remove them before I merge.

**Comment by EvanGSullivan** [comment]
@ranjeethmahankali, the checks seem to be coming from these .github workflow files: https://github.com/nTopology/libigl/blob/main/.github/workflows/continuous.yml

This code has been here all along. Maybe running on PRs automatically is a new GitHub feature.

In any case, I exorcised all the copyleft references in cmake and the tutorials that depended on those things. After a few iterations I got everything to pass at least as well as it does on main (I opened a test PR #11 to see what passes). Seems like a nice idea to keep the checks in if we can.

**Pull request merged**
